### ISSUE TITLE
Header Dashboard

### ISSUE THREAD

**Issue by MarcoBrunoBR** [CollabCodeTech/training-frontend#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Create the HeaderDashboard container whiteout the logic part.

**Describe alternatives you've considered**
No.

**Additional context**
Version mobile responsive:
![image](https://user-images.githubusercontent.com/4096456/75788043-ef897880-5d67-11ea-809b-b2874a0ad576.png)

Version desktop responsive:
![image](https://user-images.githubusercontent.com/4096456/75788092-04fea280-5d68-11ea-9a2b-b1973f2c649e.png)

Link to Figma:
https://www.figma.com/file/gL5DC1W2R9zhfCRRXAjJGn/CollabWorld.training?node-id=183%3A5

**Comment by saulonunesdev** [comment]
@MarcoBrunoBR Can you please Assign this task to me :D
