### ISSUE TITLE
Tools separator

### ISSUE THREAD

**Issue by MarcoBrunoBR** [CollabCodeTech/training-frontend#9]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Create tools separator.

**Describe alternatives you've considered**
No.

**Additional context**
Mobile and Desktop:
![image](https://user-images.githubusercontent.com/4096456/75789708-6162c180-5d6a-11ea-8474-707a3d91c377.png)

Link to figma:
https://www.figma.com/file/gL5DC1W2R9zhfCRRXAjJGn/CollabWorld.training?node-id=183%3A5

**Comment by LuizGMiranda** [comment]
Hi @MarcoBrunoBR , I commented in PR, how to look?
